name: Release project

on:
  push:
    branches:
      - release

jobs:
  buildForIOS:
    name: Build for iOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-iOS
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
      - name: Generate IPA File
        run: |
          cd build/iOS/iOS
          mkdir archive
          xcodebuild -scheme "Unity-iPhone" -target "Unity-iPhone" -sdk iphoneos -archivePath archive/iBMS.xcarchive -configuration Release archive
          cp -r archive/iBMS.xcarchive/Products/Applications/iBMS.app/ ./Payload/iBMS.app
          rm -f ./Payload/.DS_Store
          zip -r iBMS.ipa ./Payload 
      - uses: actions/upload-artifact@v3
        with:
          name: iBMS.ipa
          path: build/iOS/iOS/iBMS.ipa
