name: Release project

on:
  push:
    branches:
      - release

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.2.0
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          cacheUnityInstallationOnMac: true
      - name: Generate IPA File
        if: matrix.targetPlatform == 'iOS'
        run: |
          cd build/iOS/iOS
          mkdir archive
          xcodebuild -scheme "Unity-iPhone" -target "Unity-iPhone" -sdk iphoneos -archivePath archive/iBMS.xcarchive -configuration Release archive
          cp -r archive/iBMS.xcarchive/Products/Applications/iBMS.app/ ./Payload/iBMS.app
          rm -f ./Payload/.DS_Store
          zip -r iBMS.ipa ./Payload 
      - uses: actions/upload-artifact@v3
        if: matrix.targetPlatform == 'iOS'
        with:
          name: iBMS.ipa
          path: build/iOS/iOS/iBMS.ipa
